server:
  port: 8083

spring:
  application:
    name: rating-service

  config:
    import: "optional:configserver:http://localhost:8085"

  mongodb:
    uri: mongodb://localhost:27017/microservices
    database: microservices

#eureka:
#  instance:
#    prefer-ip-address: true
#
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
